---
params: 
    title: ""
title: "`r params$title`"
author: ""
output: teproj::word_document_te
---

```{r setup, include = FALSE}
# rmarkdown::render(file.path("R", "01-main.Rmd"))
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  include = TRUE,
  fig.align = "center",
  fig.width = 6,
  fig.height = 6,
  # out.width = 6,
  # out.height = 6,
  warning = FALSE,
  message = FALSE
)
```

I don't have MATLAB installed, and I'm better with R, so I'm using R.

```{r config}
library("tidyverse")
```

## 1

```{r}
B <-
  matrix(
    data = c(
    seq(1L, 7L, 1L),
    seq(9L, -3L, -2L),
    2L ^ seq(2L, 8L, 1L)
    ),
    nrow = 3, ncol = 7, byrow = TRUE
  )
B
```

## 2

```{r}
str <- "Need-to-break-this-string"
str %>% str_split_fixed("-", n = 5)
```


## 3

With R, (assuming `"data.csv"` exists in the working directory)

```{r eval = FALSE}
# R
readr::read_csv("data.csv", col_names = TRUE)
```

With MATLAB,

```
dlmread("data.csv", ",")
```

## 4

```{r}
a <- t(c(1, 2, 3))
b <- t(c(2, 4, 7))
a / b
b / a
```


## 5

I'll assume "matrix A" is matrix B from #1.

```{r eval = FALSE}
B[1, 3] <- 0
```


## 6

With R,

```{r eval = FALSE}
exists("a.b.c")
# Or...

```

With MATLAB,

```
ismember(a,b,c)
```

## 7

```{r}
a <- matrix(
  data =
    c(
      c(1, 4, 3, 2),
      c(-3, 4, -5, 1),
      c(5, 6, 1, 2),
      c(-2, -3, 5, 6)
    ),
  nrow = 4, ncol = 4, byrow = TRUE
)
c <- a[c(1:3), c(2:3)]
c
s <- sum(a)
s
d <- a * (a * diag(a))
d
e <- a[c(3:4), c(3:4)] * t(a[c(3:4), c(3:4)])
e
```


## 8

TRUE (because NOT(4 == 5 & 4 == 4) -> NOT(FALSE & TRUE) -> NOT(FALSE) -> TRUE)

## 9

```{r}
# v <- seq(2, 2 * 30, by = 2)
# v %*% v
(2 ^ 30) * factorial(30)
```

## 10

```
z = 4
```

## 11

twice

## 12

```
1 'men'
2 'mens'
3 'mensa'
4
5
6
7
8
9
10
```

## 13

## 14

5

## 15

```{r}
m <- matrix(0, 5, 5)
for (i in (1:5)) {
  for (j in (1:5)) {
    m[i, j] <- i + j
    m[j, i] <- m[i, j]
  }
}
m[4, 3]
```

`m[4, 3] = 7`

## 16

```{r}
k <- 0
while((k ^ 0.5) < k) {
  k <- k + 1
}
k
```

`k = 0`

## 17

## 18

```{r}
mask1 <- matrix(0, 3, 7)
mask1[, 3] <- 1
mask1[, 5] <- 1
mask1
sum((mask1 %*% t(B))[1, ])

mask2 <- matrix(0, 7, 3)
mask2[, 3] <- 1
mask2
sum(t(B) * mask2)

# ...
```


## 19

## 20

# Part II

## 1

```
select * 
from VetVisit a
left join VetVisit b
on (select PetName,  max(VisitNumber) mx 
from VetVisit group by PetName) b
where a.VisitNumber = b.mx
```

## 2

Doing this with `row_number()` (which could be used for the previous question as well),

```
with temp as
(select PetName,
row_number() over (partition by PetName order by VisitNumber desc) idx
from VetVisit)

select *
where idx = 2
```

